### ISSUE TITLE
Wind estimate error

### ISSUE THREAD

**Issue by shovan777** [prokuranepal/ardupilot#2]
## Bug report

**Issue details**

ahrs wind_estimate differs from the simulated WIND_SPD

**Version**
master branch

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
default sitl plane ariframe

**Hardware type**
sitl

**Logs**
#1 the issue was first observed while implementing payload release mode in plane
It can be seen in the image that wind speed is shown to be 20m/s at 60 deg while the wind estimate is shown to be about 9m/s at 60 deg
![drone_wind_est](https://user-images.githubusercontent.com/33648198/82309608-0f355200-99e3-11ea-9a67-dc920023fa1b.png)
This behavior was observed at different wind speed and angles. Also, a loiter action was performed in an effort to calibrate the sensor but that does not seem to have any effect.

However, after the completion of the mission when drone goes into RTL mode and loiter at the home location, it was observed that the wind speed estimate stabilized to about 20m/s at 60 deg. The behavior is shown in the below picture. 
![drone_wind_est3](https://user-images.githubusercontent.com/33648198/82309627-12c8d900-99e3-11ea-86c1-58778fc4cc9b.png)

**Comment by aabs7** [comment]
I don't think this is a bug. I think it is more of a calculation limitation in the code. The calculation estimating wind vector, inside [estimate_wind( )](https://github.com/aabs7/ardupilot/blob/cb8275e9704da3f87a7464008b016d1150f4b916/libraries/AP_AHRS/AP_AHRS_DCM.cpp#L947) function, requires a change in the attitude of the plane for correctly estimating wind speed and direction. 
So I think that in some way RTL flight mode suffices this condition and hence shows correct wind estimate.
However, I am not really sure why the plane doesn't correctly estimate wind speed and direction in the loiter mode.

**Comment by aabs7** [comment]
Further, you can read [Ardupilot_WindEstimation.pdf](https://github.com/aabs7/ardupilot/files/4686251/Ardupilot_WindEstimation.pdf). This is how wind estimation code is written in Ardupilot.
